import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    
      <Head>
        <title>Success!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

       <h1>Congratulations!</h1>

    <img src="https://www.advocatehealth.org/-/media/Project/Health-System-Enterprise/AdvocateHealthOrg/advocatehealthorg/images/headerfooter/advocatehealthorg_logo.webp?h=34&iar=0&w=300&rev=253693880f31452eaaf228bf535691e3&hash=7B12012F90295C6DA196DB78BD090978" alt="Description of GIF" />
  
  <p>Congrats, you've successfully set up an automated workflow with GitHub Actions to deploy your Next.js application to GitHub Pages! 🥳</p>
  <p>Arturo Cardenas</p>
      </main>
    </>
  )
}
