name: build-test-deploy

on: push

jobs:
  build:
    # runner engine
    runs-on: ubuntu-latest

    steps:  # reference code within this repository
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      #runner commands
      - run: npm install  #install
      - run: npm run build  #run its build
